blog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('miniblog.urls'))
]

miniblog/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = "miniblog"
urlpatterns = [
    path("", views.home, name="home"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("signup/", views.user_signup, name="signup"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("addpost/", views.user_addpost, name="addpost"),
    path("updatepost/<int:id>", views.user_updatepost, name="updatepost"),
    path("deletepost/<int:id>", views.user_deletepost, name="deletepost"),
]

miniblog/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255)
    desc = RichTextField(blank=True, null=True)

miniblog/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django import forms
from ckeditor.widgets import CKEditorWidget
from miniblog import models


class SignUpForm(UserCreationForm):
    # email = forms.EmailField(max_length=254, required=True, help_text='Required. Enter a valid email address.')
    password1 = forms.CharField(label=_("Password"),
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label=_("Password confirmation"),
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control'}),
                                help_text=_("Enter the same password as above, for verification."))

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name',
                  'last_name', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class LoginForm(AuthenticationForm):
    class Meta:
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }


class PostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'desc']
        labels = {'title': 'Title', 'desc': "Description"}
        widgets = {'title': forms.TextInput(attrs={'class': 'form-control'}),
                   'desc': forms.Textarea(attrs={'class': 'form-control'}), }

miniblog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from miniblog.forms import LoginForm, PostForm, SignUpForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

from miniblog.models import Post

# Create your views here.


def index(request):
    return render(request, 'miniblog/base.html', {})


def home(request):
    posts = Post.objects.all()
    return render(request, 'miniblog/home.html', {'posts': posts})


def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


def dashboard(request):
    posts = Post.objects.all()
    return render(request, 'miniblog/dashboard.html', {'posts': posts})


def user_signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'You have successfully signed up!')
            # login(request, user)
            # return HttpResponseRedirect('/')
    else:
        form = SignUpForm()
    return render(request, 'miniblog/signup.html', {'form': form})


def user_login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = LoginForm(request=request, data=request.POST)
            if form.is_valid():
                uname = form.cleaned_data['username']
                upass = form.cleaned_data['password']
                user = authenticate(request, username=uname, password=upass)
                if user is not None:
                    login(request, user)
                    return HttpResponseRedirect('/dashboard/')
        else:
            form = LoginForm()
        return render(request, 'miniblog/login.html', {'form': form})
    else:
        return HttpResponseRedirect('/dashboard/')


def user_addpost(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            fm = PostForm(request.POST)
            if fm.is_valid():
                utitle = fm.cleaned_data['title']
                udesc = fm.cleaned_data['desc']
                form = Post(title=utitle, desc=udesc)
                form.save()
                form = PostForm()
        else:
            form = PostForm()
        return render(request, 'miniblog/addpost.html', {'form': form})
    else:
        return HttpResponseRedirect('/login/')


def user_updatepost(request, id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            pi = Post.objects.get(pk=id)
            form = PostForm(request.POST, instance=pi)
            if form.is_valid():
                form.save()
        else:
            pi = Post.objects.get(pk=id)
            form = PostForm(instance=pi)
        return render(request, 'miniblog/updatepost.html', {'form': form})
    else:
        return HttpResponseRedirect('/login/')


def user_deletepost(request, id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            pi = Post.objects.get(pk=id)
            pi.delete()
            return HttpResponseRedirect('/dashboard/')
    else:
        return HttpResponseRedirect('/login/')

miniblog/templates/miniblog/addpost.html
{% extends 'miniblog/base.html' %} {% load static %} {% block content %}

<div class="col-sm-10">
  <h3 class="text-white">Add Post</h3>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{form.media}}
    {{form.as_p}}
    <input type="submit" value="Add" class="btn btn-success">
    <a href="{% url 'miniblog:dashboard' %}" class="btn btn-danger">Cancel</a>
   </form>
</div>

{% endblock content %}

miniblog/templates/miniblog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link href="{% static 'miniblog/css/bootstrap.css' %}" rel="stylesheet" />
    <link href="{% static 'miniblog/css/style.css' %}" rel="stylesheet" />
  </head>
  <body>
    <div class="container-fluid bg-dark">
      {% include 'miniblog/navbar.html' %}
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% block msg %}
                {% endblock msg %}
            </div>
        </div>

        <div class="row">
            {% block side %}
            {% endblock side %}

            {% block content %}
            {% endblock content %}
        </div>
    </div>

    <script src="{% static 'miniblog/js/jquery.js' %}"></script>
    <script src="{% static 'miniblog/js/popper.js' %}"></script>
    <script src="{% static 'miniblog/js/bootstrap.js' %}"></script>
  </body>
</html>

miniblog/templates/miniblog/dashboard.html
{% extends 'miniblog/base.html' %} {% load static %} {% block msg %} 
{% if messages %} 
{% for message in messages %}
<div
  {% if message.tags %}
    class="alert alert-{{message.tags}} alert-dismissible fade show"
  {% endif %}
>
  <strong>{{message}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %} 
{% endif %} {% endblock msg %} {% block side %}
{% comment %} <div class="col-sm-2 text-white my-5 text-center">
  <h4 class="my-5">Profile</h4>
  <h5>{{full_name}}</h5>
  {% for group in groups %}
  <p>{{group.name}}</p>
  {% endfor %}
</div> {% endcomment %}
{% endblock side %} {% block content %}
<div class="col-sm-10">
  <h3 class="text-white">Dashboard</h3>
  <a href="{% url 'miniblog:addpost' %}" class="btn btn-success">Add Post</a>
  <h4 class="text-center alert alert-info mt-3">Show Post Information</h4>
  {% if posts %}
  <table class="table table-hover bg-white">
    <thead>
      <tr class="text-center">
        <th scope="col" style="width: 2%">ID</th>
        <th scope="col" style="width: 28%">Title</th>
        <th scope="col" style="width: 55%">Description</th>
        <th scope="col" style="width: 15%">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for post in posts %}
      <tr>
        <th scope="row">{{post.id}}</th>
        <td>{{post.title}}</td>
        <td>{{post.desc | safe}}</td>
        <td class="text-center">
          <a
            href="{% url 'miniblog:updatepost' post.id %}"
            class="btn btn-warning btn-sm"
            >Edit</a
          >
          {% if perms.blog.delete_post %}
          <form
            action="{% url 'miniblog:deletepost' post.id %}"
            method="post"
            class="d-inline"
          >
            {% csrf_token %}
            <input type="submit" class="btn btn-danger btn-sm" value="Delete" />
          </form>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% else %}
  <h4 class="text-center alert alert-warning">No Records</h4>
  {% endif %}
</div>
{% endblock content %}

miniblog/templates/miniblog/home.html
{% extends 'miniblog/base.html' %} {% load static %} {% block content %}

<div class="col-sm-10">
  <h3 class="text-white">Home Page</h3>
  {% for post in posts %}
  <div class="jumbotron my-5">
    <div class="container">
      <h1 class="display-4 font-weight-bold">{{post.title}}</h1>
      <p class="lead">{{post.desc | safe}}</p>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}

miniblog/templates/miniblog/login.html
{% extends 'miniblog/base.html' %} 
{% load static %} 
{% block content %} 
    <div class="col-sm-10">
        <h3 class="text-white">Login</h3>
        {% if messages %}
        {% for message in messages %}
            <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}}</p>
        {% endfor %}
        {% endif %}
        <form action="" method="post" novalidate>
            {% csrf_token %} 
            {% for fm in form %}
                <div class="form-group">
                    {{fm.label_tag}} {{ fm }} <small class="text-warning">{{fm.errors|striptags}}</small>
                </div>
            {% endfor %}
            <input type="submit" class='btn btn-primary' value="Login">
            {% if form.non_field_errors %}
               {% for error in form.non_field_errors %}
                  <p class="alert alert-danger my-3">{{error}}</p>
               {% endfor %}
            {% endif %}
          </form>
    </div>
{% endblock content %}

miniblog/templates/miniblog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Mini Blog</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{% url 'miniblog:home' %}">Home</a>
        {% if request.user.is_authenticated %}
        <a class="nav-link" href="{% url 'miniblog:dashboard' %}">Dashboard</a>
        <a class="nav-link" href="{% url 'miniblog:logout' %}">Logout</a>
        {% else %}
        <a class="nav-link" href="{% url 'miniblog:signup' %}">Signup</a>
        <a class="nav-link" href="{% url 'miniblog:login' %}">Login</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>

miniblog/templates/miniblog/signup.html
{% extends 'miniblog/base.html' %} {% load static %} {% block content %}

<div class="col-sm-10">
  <h3 class="text-white">SignUp</h3>
    {% if messages %}
    {% for message in messages %}
        <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}}</p>
    {% endfor %}
    {% endif %}
    <form action="" method="post" novalidate>
    {% csrf_token %} {% for fm in form %}
    <div class="form-group">
      {{fm.label_tag}} {{ fm }} <small class="text-warning">{{fm.errors|striptags}}</small>
    </div>
    {% endfor %}
    <input type="submit" class="btn btn-primary" value="SignUp" />
    {% if form.non_field_errors %} {% for error in form.non_field_errors %}
    <p class="alert alert-danger my-3">{{error}}</p>
    {% endfor %} {% endif %}
  </form>
</div>

{% endblock content %}

miniblog/templates/miniblog/updatepost.html
{% extends 'miniblog/base.html' %} {% load static %} {% block content %}

<div class="col-sm-10">
  <h3 class="text-white">Update Post</h3>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{form.media}}
    {{form.as_p}}
    <input type="submit" value="Update" class="btn btn-success">
    <a href="{% url 'miniblog:dashboard' %}" class="btn btn-danger">Cancel</a>
   </form>
</div>

{% endblock content %}